'use strict';

import { writeFileSync } from 'fs';

import { ATT_CLASS_ON, ATT_VARIABLE_TITLE_LEFT, ATT_VARIABLE_TITLE_RIGHT, ATT_VARIABLE_TITLE_TOP } from '@src/ts/core/style.tokens.js';

const lines = [
    `// WARNING: These constants are autogenerated from src\\ts\\style.tokens.ts single source`,
    `// with the .delivery\\scripts\\generate-style-constants.ts script.`,
    `@abbr-title-top-variable: ${ATT_VARIABLE_TITLE_TOP};`,
    `@abbr-title-left-variable: ${ATT_VARIABLE_TITLE_LEFT};`,
    `@abbr-title-right-variable: ${ATT_VARIABLE_TITLE_RIGHT};`,
    `@class-title-on: ${ATT_CLASS_ON};`,
];

writeFileSync('src/styles/readonly/_constants.less', lines.join('\n'));
